typedef struct {
    char *name;
    unsigned char number;
} instruction;

instruction instrSet[] = {
    {"CHAR", 1},
    {"INT", 2},
    {"STRING", 3},
    {"FLOAT", 4},
    {"SET", 5},
    {"GET", 6},
    {"INCREMENT", 7},
    {"DECREMENT", 8},
    {"PLUS", 9},
    {"MINUS", 10},
    {"TIMES", 11},
    {"DIVIDEDBY", 12},
    {"MODULUS", 13},
    {"UNARYMINUS", 14},
    {"EQUALS", 15},
    {"NOTEQUALS", 16},
    {"LESSTHAN", 17},
    {"LESSTHANOREQUALS", 18},
    {"GREATERTHAN", 19},
    {"GREATERTHANOREQUALS", 20},
    {"LOGICALAND", 21},
    {"LOGICALOR", 22},
    {"LOGICALXOR", 23},
    {"LOGICALNOT", 24},
    {"BITWISEAND", 25},
    {"BITWISEOR", 26},
    {"BITWISEXOR", 27},
    {"BITWISENOT", 28},
    {"TOCHAR", 29},
    {"TOINT", 30},
    {"TOFLOAT", 31},
    {"ROUND", 32},
    {"FLOOR", 33},
    {"CEIL", 34},
    {"MIN", 35},
    {"MAX", 36},
    {"ABS", 37},
    {"CONSTRAIN", 38},
    {"MAP", 39},
    {"POW", 40},
    {"SQ", 41},
    {"SQRT", 42},
    {"DELAY", 43},
    {"DELAYUNTIL", 44},
    {"MILLIS", 45},
    {"PINMODE", 46},
    {"ANALOGREAD", 47},
    {"ANALOGWRITE", 48},
    {"DIGITALREAD", 49},
    {"DIGITALWRITE", 50},
    {"PRINT", 51},
    {"PRINTLN", 52},
    {"OPEN", 53},
    {"CLOSE", 54},
    {"WRITE", 55},
    {"READINT", 56},
    {"READCHAR", 57},
    {"READFLOAT", 58},
    {"READSTRING", 59},
    {"IF", 128},
    {"ELSE", 129},
    {"ENDIF", 130},
    {"WHILE", 131},
    {"ENDWHILE", 132},
    {"LOOP", 133},
    {"ENDLOOP", 134},
    {"STOP", 135},
    {"FORK", 136},
    {"WAITUNTILDONE", 137}
};

int noOfInstr = sizeof(instrSet) / sizeof(instruction);